# Generated by Django 3.2.5 on 2021-08-15 23:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('price', models.FloatField(max_length=255)),
                ('details', models.CharField(max_length=255, verbose_name=255)),
                ('huespedes', models.CharField(max_length=255, verbose_name='Huespedes')),
                ('habitaciones', models.CharField(max_length=255, verbose_name='Rooms')),
                ('detalles', models.CharField(max_length=255, verbose_name='detalles')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a product image', upload_to='images/')),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='airbnb.cities')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Products Image',
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ciudades')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parents', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='airbnb.ciudades')),
            ],
            options={
                'verbose_name': 'Ciudades',
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='ciudades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='airbnb.ciudades'),
        ),
    ]
