# Generated by Django 3.2.5 on 2021-08-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudades',
            old_name='parents',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='habitaciones',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='huespedes',
        ),
        migrations.AddField(
            model_name='ciudades',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cities',
            name='details',
            field=models.CharField(max_length=255, verbose_name='detail'),
        ),
    ]
