# Generated by Django 3.2.5 on 2021-08-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb', '0002_auto_20210815_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='details',
        ),
    ]
